/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.6
 * Generated at: 2017-01-19 07:03:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("   <!-- Theme Made By www.w3schools.com - No Copyright -->\r\n");
      out.write("  <title>Home</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script> \r\n");
      out.write("<!--   <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  -->\r\n");
      out.write("  \r\n");
      out.write("  <style>\r\n");
      out.write("  \r\n");
      out.write("  body {\r\n");
      out.write("        \r\n");
      out.write("    background:url('http://www.wallpaperup.com/uploads/wallpapers/2012/10/21/20181/cad2441dd3252cf53f12154412286ba0.jpg');\r\n");
      out.write("    padding:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg-4 {\r\n");
      out.write("      background-color: #2f2f2f; /* Black Gray */\r\n");
      out.write("      color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("#login-dp{\r\n");
      out.write("    min-width: 250px;\r\n");
      out.write("    padding: 14px 14px 0;\r\n");
      out.write("    overflow:hidden;\r\n");
      out.write("    background-color:rgba(255,255,255,.8);\r\n");
      out.write("}\r\n");
      out.write("#login-dp .help-block{\r\n");
      out.write("    font-size:12px    \r\n");
      out.write("}\r\n");
      out.write("#login-dp .bottom{\r\n");
      out.write("    background-color:rgba(255,255,255,.8);\r\n");
      out.write("    border-top:1px solid #ddd;\r\n");
      out.write("    clear:both;\r\n");
      out.write("    padding:14px;\r\n");
      out.write("}\r\n");
      out.write("#login-dp .social-buttons{\r\n");
      out.write("    margin:12px 0    \r\n");
      out.write("}\r\n");
      out.write("#login-dp .social-buttons a{\r\n");
      out.write("    width: 49%;\r\n");
      out.write("}\r\n");
      out.write("#login-dp .form-group {\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write(".btn-fb{\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background-color:#3b5998;\r\n");
      out.write("}\r\n");
      out.write(".btn-fb:hover{\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background-color:#496ebc \r\n");
      out.write("}\r\n");
      out.write(".btn-tw{\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background-color:#55acee;\r\n");
      out.write("}\r\n");
      out.write(".btn-tw:hover{\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background-color:#59b5fa;\r\n");
      out.write("}\r\n");
      out.write("@media(max-width:768px){\r\n");
      out.write("    #login-dp{\r\n");
      out.write("        background-color: inherit;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    #login-dp .bottom{\r\n");
      out.write("        background-color: inherit;\r\n");
      out.write("        border-top:0 none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write(" <style>\r\n");
      out.write("    <script src=\"//code.jquery.com/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("    <script src=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        window.alert = function(){};\r\n");
      out.write("        var defaultCSS = document.getElementById('bootstrap-css');\r\n");
      out.write("        function changeCSS(css){\r\n");
      out.write("            if(css) $('head > link').filter(':first').replaceWith('<link rel=\"stylesheet\" href=\"'+ css +'\" type=\"text/css\" />'); \r\n");
      out.write("            else $('head > link').filter(':first').replaceWith(defaultCSS); \r\n");
      out.write("        }\r\n");
      out.write("        $( document ).ready(function() {\r\n");
      out.write("          var iframe_height = parseInt($('html').height()); \r\n");
      out.write("          window.parent.postMessage( iframe_height, 'http://bootsnipp.com');\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("  \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <div class=\"container-fluid bg-1 text-center\">\r\n");
      out.write("  <b class=\"heading\" style=\"font-size:75px;color: white;text-shadow:2px 2px 4px #000000;\">Ammus Arts& Craft</b>    \r\n");
      out.write("  </div><br>\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-inverse\" role=\"navigation\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">Home</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("      <ul class=\"nav navbar-nav\">\r\n");
      out.write("        <li class=\"active\"><a href=\"images\">Images</a></li>\r\n");
      out.write("        <li><a href=\"products\">Products</a></li>\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Details <span class=\"caret\"></span></a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("            <li><a href=\"#\">About us</a></li>\r\n");
      out.write("            <li><a href=\"contact\">Contact Us</a></li>\r\n");
      out.write("            <li><a href=\"#\"></a></li>\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <form class=\"navbar-form navbar-left\" role=\"search\">\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" placeholder=\"Search\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("      </form>\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("        <li><a href=\"register\">Register</a></li>\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("          <li><a href=\"login\">Login</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("          \r\n");
      out.write("          <br>\r\n");
      out.write("          <br>\r\n");
      out.write("</body>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  \r\n");
      out.write("  </script>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid bg-2 text-center\">\r\n");
      out.write("  <div class=\"col-sm-8\">\r\n");
      out.write("    <h2><font color=\"red\"> Mural Paint</font></h2>\r\n");
      out.write("     \r\n");
      out.write("      <p><h4><font color=\"white\">Murals of sorts date to Upper Paleolithic times such as the paintings in the Chauvet Cave in ArdÃ¨che department of southern France (around 30,000 BC). Many ancient murals have survived in Egyptian tombs (around 3150 BC),[2] the Minoan palaces (Middle period III of the Neopalatial period, 1700â1600 BC) and in Pompeii (around 100 BC â AD 79).\r\n");
      out.write("\r\n");
      out.write("      During the Middle Ages murals were usually executed on dry plaster (secco). The huge collection of Kerala mural painting dating from the 14th century are examples of fresco secco.[3][4] In Italy, circa 1300, the technique of painting of frescos on wet plaster was reintroduced and led to a significant increase in the quality of mural painting.[5]</font></h4></p>\r\n");
      out.write("      <br><br>\r\n");
      out.write("\r\n");
      out.write("      <h2><font color=\"red\"> Glass Paint</font></h2>\r\n");
      out.write("     \r\n");
      out.write("      <p><h4><font color=\"white\">A Class Painting is not just an ordinary painting contractor. Located in Miami, We are totally committed to your complete satisfaction and rely fully on our clients satisfaction, therefore this is why we are so committed to you when you trust us with your project. We know that you had other choices before you contacted us, and this is why we are so appreciative of your choice. Rest assure âWe want your business!â because leaving you with an smile at the end of each job, is what makes us happy and thatâs when our satisfaction starts. When it comes to us 100% Customer Service is just the tip of the iceberg. Our clients are the backbone of our business and we love to treat them with the highest dignity and respect.</font></h4></p>\r\n");
      out.write("      <br><br>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("            <iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/kR-J2JqLH88\" frameborder=\"0\" allowfullscreen></iframe>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("    <!-- Indicators -->\r\n");
      out.write("    <ol class=\"carousel-indicators\">\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"3\"></li>\r\n");
      out.write("    </ol>\r\n");
      out.write("\r\n");
      out.write("    <!-- Wrapper for slides -->\r\n");
      out.write("    <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("      <div class=\"item active\">\r\n");
      out.write("        <img src=\"resources/images/carousal.jpg\" alt=\"Chania\" width=\"1000\">\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"resources/images/carosal2.jpg\" alt=\"Chania\" width=\"1000\">\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"resources/images/carouasl3.jpg\" alt=\"Flower\" width=\"1000\">\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"resources/images/carousal1.jpg\" alt=\"Flower\" width=\"1000\">\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("       <div class=\"item\">\r\n");
      out.write("        <img src=\"resources/images/carosal4.jpg\" alt=\"Flower\" width=\"1000\">\r\n");
      out.write("      </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</br>\r\n");
      out.write("</br>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"circle\">\r\n");
      out.write("      <a href=\"propage\">\r\n");
      out.write("        <img src=\"resources/images/images (6).jpg\" class=\"img-circle\"  alt=\"Cinque Terre\" width=\"304\" height=\"240\">\r\n");
      out.write("        <div class=\"caption\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"circle\">\r\n");
      out.write("      <a href=\"propage\">\r\n");
      out.write("        <img src=\"resources/images/IMG-3.jpg\" class=\"img-circle\"  alt=\"Cinque Terre\" width=\"304\" height=\"240\">\r\n");
      out.write("        <div class=\"caption\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"circle\">\r\n");
      out.write("      <a href=\"propage\">\r\n");
      out.write("        <img src=\"resources/images/IMG4.jpg\" class=\"img-circle\"  alt=\"Cinque Terre\" width=\"304\" height=\"240\">\r\n");
      out.write("        <div class=\"caption\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<footer style=\"height:13px;color:#ddd;align:center;background:black\">\r\n");
      out.write("<div class=\"container-fluid bg-4 text-center\">\r\n");
      out.write("\r\n");
      out.write(" <div class=\"row\"> \r\n");
      out.write("\t<div class=\"col-sm-6\" >\r\n");
      out.write("              <div id=\"meta-4\" class=\"widget widgetFooter widget_meta\">\r\n");
      out.write("              <h4 class=\"widgettitle\">Subscribe :</h4>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                  <span class=\"input-group-addon\">E-mail :</span>\r\n");
      out.write("                  <input class=\"form-control\" placeholder=\"Write your email ..\" type=\"text\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                  <span class=\"input-group-addon\">Phone  :</span>\r\n");
      out.write("                  <input class=\"form-control\" placeholder=\"+96777000000\" type=\"text\">\r\n");
      out.write("                   <span class=\"input-group-btn\">\r\n");
      out.write("                    <button class=\"btn btn-primary\" type=\"button\">Subscribe !</button>\r\n");
      out.write("                  </span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\t\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("    <div class=\"col-sm-6\">\r\n");
      out.write("\t <h1 class=\"title-widget\">Contact Detail </h1>\r\n");
      out.write("                                \r\n");
      out.write("                            <div class=\"footerp\"> \r\n");
      out.write("                                \r\n");
      out.write("                                <h2 class=\"title-median\">AMMUS ARTS&CRAFT</h2>\r\n");
      out.write("                                <p><b>Email id:</b> <a href=\"mailto:info@ammusarts&craft.com\">info@ammusarts&carft.com</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><b>Postal Address</b></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><b>Phone Numbers : </b>7042827160, </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p> 011-27568832, 9868387223</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <hr>\r\n");
      out.write("        <div class=\"text-center center-block\">\r\n");
      out.write("            <p class=\"txt-railway\"> www.ammusarts&craft.com </p>\r\n");
      out.write("           \r\n");
      out.write("                 <a href=\"https://www.facebook.com/\"><i id=\"social-fb\" class=\"fa fa-facebook-square fa-3x social\"></i></a>\r\n");
      out.write("              <a href=\"https://twitter.com/login\"><i id=\"social-tw\" class=\"fa fa-twitter-square fa-3x social\"></i></a>\r\n");
      out.write("              <a href=\"https://plus.google.com\"><i id=\"social-gp\" class=\"fa fa-google-plus-square fa-3x social\"></i></a>\r\n");
      out.write("              <a href=\"mailto:bootsnipp@gmail.com\"><i id=\"social-em\" class=\"fa fa-envelope-square fa-3x social\"></i></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    <hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br />\r\n");
      out.write("<p> Copyright Â© 2016 Internal. All Rights Reserved.</p>\r\n");
      out.write("</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
